name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  qa:
    uses: straw-hat-team/github-actions-workflows/.github/workflows/elixir-quality-assurance.yml@v1.6.3
    with:
      elixir-version: '1.14'
      otp-version: '24.3'
      credo-enabled: false
      dialyzer-enabled: false
